const USER_ROLE_INT = 1;
const ADMIN_ROLE_INT = 2;

const BORROWED_STATUS = ['Dibatalkan', 'Pending', 'Disetujui']
const BORROWED_STATUS_CANCELLED_INT = 0;
const BORROWED_STATUS_PENDING_INT = 1;
const BORROWED_STATUS_ACCEPTED_INT = 2;

const INPUT_TIME_STEP = 300;

const USER_ROLE_MAPPING = [
    {
        id: USER_ROLE_INT,
        name: 'User'
    },
    {
        id: ADMIN_ROLE_INT,
        name: 'Admin'
    }
]

export { USER_ROLE_INT, ADMIN_ROLE_INT, USER_ROLE_MAPPING, BORROWED_STATUS, BORROWED_STATUS_CANCELLED_INT, BORROWED_STATUS_PENDING_INT, BORROWED_STATUS_ACCEPTED_INT, INPUT_TIME_STEP }