export {
  ADMIN_ROLE,
  ADMIN_ROLE_INT,
  ADMIN_VIEWER_ROLE,
  AGREEMENT_STATUS_ACCEPTED,
  AGREEMENT_STATUS_DECLINED,
  AGREEMENT_STATUS_DISPLAY,
  BORROWED_STATUS,
  BORROWED_STATUS_ACCEPTED,
  BORROWED_STATUS_ACCEPTED_INT,
  BORROWED_STATUS_BADGE_CLASSES,
  BORROWED_STATUS_CANCELED,
  BORROWED_STATUS_CANCELLED_INT,
  BORROWED_STATUS_FILTER_OPTIONS,
  BORROWED_STATUS_LABELS,
  BORROWED_STATUS_PENDING,
  BORROWED_STATUS_PENDING_INT,
  getBorrowedStatusLabel,
  USER_ROLE,
  USER_ROLE_INT,
  USER_ROLE_MAPPING,
} from "./status";

export type { AgreementStatus, BorrowedStatus, UserRole } from "./status";

const INPUT_TIME_STEP = 60 * 30;

export { INPUT_TIME_STEP };
